#!/bin/bash

clear

CURRENT_DIR=$(pwd)

cd ~/HW1/sample/benchmarks/583$1/src

rm llvmprof.out # Otherwise your profile runs are added together

clang -emit-llvm -o $1.bc -c $1.c || { echo "Failed to emit llvm bc"; exit 1; }

opt -insert-edge-profiling $1.bc -o $1.profile.bc

llc $1.profile.bc -o $1.profile.s

g++ -o $1.profile $1.profile.s ../../../Release+Asserts/lib/libprofile_rt.so 

./$1.profile $2 > /dev/null

cd $CURRENT_DIR

