#!/bin/bash

clear

CURRENT_DIR=$(pwd)

cd ~/HW1/sample/benchmarks/583$1/src

rm llvmprof.out # Otherwise your profile runs are added together

clang -emit-llvm -o $1.bc -c $1.c || { echo "Failed to emit llvm bc"; exit 1; }

opt -insert-edge-profiling $1.bc -o $1.profile.bc

llc $1.profile.bc -o $1.profile.s

g++ -o $1.profile $1.profile.s /opt/llvm/Release+Asserts/lib/libprofile_rt.so 

rm ~/HW1/sample/benchmarks/583$1/input1/*

cp ~/HW1/benchmarks/583$1/input1/* ~/HW1/sample/benchmarks/583$1/input1

./$1.profile ../input1/* > /dev/null

cd $CURRENT_DIR

(opt -load ../../Release+Asserts/lib/hw1pass1.so -profile-loader -profile-info-file=../../benchmarks/583$1/src/llvmprof.out -hw1pass1 < ../../benchmarks/583$1/src/$1.bc > /dev/null) 2>&1 | tee ~/HW1/tzachari_hw1/583$1.opcstats

cp hw1pass1.cpp ~/HW1/tzachari_hw1/

cd ~/HW1

tar -cvzf tzachari_hw1.tgz tzachari_hw1

cd $CURRENT_DIR
